apiVersion: v1
kind: ConfigMap
metadata:
  name: lab-grafana-config
  namespace: dst-lab
data:
  prometheus-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://lab-prometheus:9090
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://lab-loki:3100
        basicAuth: false
        editable: true
        isDefault: false
        

