{
 "title": "DST - Physical Cluster Metrics",
 "description": "add phy_interface filter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "phy_interface", "label": "Ethernet_Interface", "query": { "query": "label_values(device)" } },
   { "name": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Compute (CPU/RAM)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM (Total)",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(node_memory_MemTotal_bytes{node=~\"$node\",job=\"kubernetes-hosts\"})) by (node)"
    }
   ]
  },
  {
   "title": "RAM Used (Total)",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  sum(node_memory_MemAvailable_bytes{job=\"kubernetes-hosts\", node=~\"$node\"})\n  /\n  sum(node_memory_MemTotal_bytes{job=\"kubernetes-hosts\", node=~\"$node\"})\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores (Total)",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{node=~\"$node\", job=\"kubernetes-hosts\"}) by (cpu,node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy (Total)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", node=~\"$node\",job=\"kubernetes-hosts\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (node_memory_MemTotal_bytes{node=~\"$node\",job=\"kubernetes-hosts\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum (node_memory_MemTotal_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) - sum(node_memory_MemFree_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) - (sum(node_memory_Cached_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) + sum(node_memory_Buffers_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) + sum(node_memory_SReclaimable_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) + sum(node_memory_Buffers_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) + sum(node_memory_SReclaimable_bytes{node=~\"$node\",job=\"kubernetes-hosts\"})",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{node=~\"$node\",job=\"kubernetes-hosts\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(sum(node_memory_SwapTotal_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}) - sum(node_memory_SwapFree_bytes{node=~\"$node\",job=\"kubernetes-hosts\"}))",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\"}) by (cpu,node)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\"}) by (cpu,node)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\"}) by (cpu,node)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\"}) by (cpu,node)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\"}) by (cpu,node)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{node=~\"$node\",job=\"kubernetes-hosts\"}) by (cpu,node)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network (DL/UL Throughput, RTT)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Downlink Throughput (Phy)",
   "type": "timeseries",
   "description": "DL of Phyisical interfaces",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kubernetes-hosts\", device=~\"$phy_interface\", node=~\"$node\"}[$__rate_interval]) * 8) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Throughput (Phy)",
   "type": "timeseries",
   "description": "Physical UL Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kubernetes-hosts\", device=~\"$phy_interface\", node=~\"$node\"}[$__rate_interval]) * 8) by (node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}