{
 "title": "DST - NimP2P Experiments",
 "description": "add phy_interface filter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "experiment",
    "query": {
     "query": "label_values({job=\"cadvisor-full\"},container_label_app_kubernetes_io_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values({job=\"cadvisor-full\", container_label_app_kubernetes_io_name=\"$experiment\"},container_label_io_kubernetes_pod_name)"
    }
   },
   { "name": "container", "query": "nimp2p, rtt-exporter" },
   { "name": "phy_interface", "label": "eth", "query": { "query": "label_values(interface)" } },
   { "name": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Compute (CPU/RAM)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM (Total)",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"kubernetes-hosts\"})"
    }
   ]
  },
  {
   "title": "RAM Used (%)",
   "type": "gauge",
   "description": "RAM memory used by experiment pods",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(container_memory_usage_bytes{job=\"cadvisor-full\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\"})\n  /\n  sum(node_memory_MemTotal_bytes{job=\"kubernetes-hosts\", node=~\"$node\"})\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores (Total)",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{node=~\"$node\", job=\"kubernetes-hosts\"}) by (cpu,node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(sum (\n  rate(container_cpu_usage_seconds_total{\n    job=\"cadvisor-full\",\n    container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\"\n  }[$__rate_interval])\n)*100)/sum(machine_cpu_cores{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Used (Bytes)",
   "type": "stat",
   "description": "RAM memory used by experiment pods",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"cadvisor-full\", container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Time (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(sum (\n  (container_cpu_usage_seconds_total{\n    job=\"cadvisor-full\",\n    container_label_io_kubernetes_pod_name=~\"$pod\",     container_label_io_kubernetes_container_name=~\"$container\"\n  })\n))"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "description": "Only for NimP2P Container (the sidecar is not taken into account)",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{job=\"cadvisor-full\",container_label_io_kubernetes_pod_name=~\"$pod\",\ncontainer_label_io_kubernetes_container_name=~\"$container\"}) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod CPU usage (5m avg)",
   "type": "timeseries",
   "description": "Only for NimP2P Container (the sidecar is not taken into account)",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{job=\"cadvisor-full\", image!=\"\",container_label_io_kubernetes_pod_name=~\"$pod\", container_label_io_kubernetes_container_name=~\"$container\"}[5m])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network (DL/UL Throughput, RTT)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Downlink Throughput ",
   "type": "timeseries",
   "description": "DL of pods",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval]) * 8) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink Packet Throughput ",
   "type": "timeseries",
   "description": "DL PKT/s",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink Packets Dropped ",
   "type": "timeseries",
   "description": "DL PKT/s",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downlink Byte Errors ",
   "type": "timeseries",
   "description": "DL Byte Error events",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_errors_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Throughput",
   "type": "timeseries",
   "description": "UL of Pods",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval]) * 8) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Packet Throughput ",
   "type": "timeseries",
   "description": "UL PKT/s",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Packets Dropped ",
   "type": "timeseries",
   "description": "UL dropped PKTS",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplink Byte Errors ",
   "type": "timeseries",
   "description": "UL Byte Error events",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_errors_total{job=\"cadvisor-full\", interface=~\"$phy_interface\", container_label_app_kubernetes_io_name=\"$experiment\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod\"}[$__rate_interval])) by (container_label_io_kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTT (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pod_name) (\n  avg_over_time(\n    probe_icmp_duration_seconds{job=\"kubernetes-pods-rtt\", pod_name=~\"$pod\", phase=\"rtt\"}[$__rate_interval]\n  ) * 1000\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}