{
 "title": "DST - NimP2P Log",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "experiment",
    "query": {}
   },
   {
    "name": "pod",
    "query": {}
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Message Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({experiment=~\"$experiment\", instance=~\"$pod\"} |~ \"(?i)(error|fail|fatal|panic)\"[$__interval])) \n",
     "legendFormat": "error"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({experiment=~\"$experiment\", instance=~\"$pod\"} |~ \"(?i)warn\"[$__interval]))",
     "legendFormat": "warn"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({experiment=~\"$experiment\", instance=~\"$pod\"} |~ \"(?i)stdout\"[$__interval]))",
     "legendFormat": "info"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({experiment=~\"$experiment\", instance=~\"$pod\"} |~ \"(?i)debug\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time({experiment=~\"$experiment\", instance=~\"$pod\"} |= \"Sending message\"[$__range])\n) by (instance) "
    }
   ]
  },
  {
   "title": "Raw Output",
   "type": "logs",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{experiment=~\"$experiment\",instance=~\"$pod\"} |= \"$search\"",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}