kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: node-exporter-host
  namespace: dst-lab
  labels:
    app.kubernetes.io/component: exporter-host
    app.kubernetes.io/name: node-exporter-host
 
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter-host
      app.kubernetes.io/name: node-exporter-host
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter-host
        app.kubernetes.io/name: node-exporter-host
    spec:
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: ''
        - name: root
          hostPath:
            path: /
            type: ''
      containers:
        - name: node-exporter
          image: prom/node-exporter
          args:
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/host/root'
            - '--no-collector.wifi'
            - '--no-collector.hwmon'
            - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)'
            - '--collector.netclass.ignored-devices=^(veth.*)$'
          ports:
            - hostPort: 9100
              containerPort: 9100
              protocol: TCP
          resources:
            limits:
              cpu: "0.25"
              memory: 180Mi
            requests:
              cpu: "0.1"
              memory: 180Mi
          volumeMounts:
            - name: sys
              readOnly: true
              mountPath: /host/sys
              mountPropagation: HostToContainer
            - name: root
              readOnly: true
              mountPath: /host/root
              mountPropagation: HostToContainer
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      hostNetwork: true
      securityContext: {}
